# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8817380444e0d5f327272d615f066938be24807b754a95d2e098691306213b6a1fa95d9816381c54b3e3206958d64f804ddf78dc7d82e49e35a6f86cf2ea6491

test:
  secret_key_base: 42975229b4e1b47e8f4a535bc01421e58f85ee6c13fb726f4c430a81dd5c63b5f2cd795b3ec4ac2b379bfc6848fc7776edded544a7d0962dfad5fbe2bb6ca77f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
